schema_version = "1.0.0"

id = "trimmer"
version = "0.2.2"
name = "Trimmer"
tagline = "Simplified texturing workflow for trim-sheets"
maintainer = "Laas Hendrik Lumberg"
type = "add-on"

blender_version_min = "2.80.0"

license = ["GPL-3.0"]