schema_version = "1.0.0"

id = "trimmer"
version = "0.2.4"
name = "Trimmer"
tagline = "Simplified texturing workflow for trim-sheets"
maintainer = "Laas Hendrik Lumberg"
type = "add-on"

blender_version_min = "4.2.0"
tags = ["UV", "User Interface"]

license = ['SPDX:GPL-3.0-or-later']