[blender_extension]
version = "0.2.2"
blender_version_min = "2.80"
blender_version_max = "4.2.2"

[addon]
module = "trimmer"
display_name = "Trimmer"
author = "Laas Hendrik Lumberg"
description = "Allows easier positioning of UVs on texture atlas and trim-sheet based texture sheets"
category = "UV"
id = "trimmer"  # This should be fine, but consider something more specific if you plan to expand or avoid conflicts in the future
license = "GPL-3.0"
maintainer = "Laas Hendrik Lumberg"
name = "Trimmer"
schema_version = 2
tagline = "Simplified texturing workflow for trim-sheets"
type = "python"
